Controllers/CarroController.cs
using CarRent.Models;
using CarRent.Repositories.Interfaces;
using CarRent.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace CarRent.Controllers
{
    public class CarroController : Controller
    {
        private readonly ICarRentReposityory _carRentReposityory;

        public CarroController(ICarRentReposityory carRentReposityory)
        {
            _carRentReposityory = carRentReposityory;
        }

        public IActionResult List(string categoria)
        {
            IEnumerable<Carro> carros;
            string categoriaAtual = string.Empty;

            if(string.IsNullOrEmpty(categoria))
            {
                carros = _carRentReposityory.Carros.OrderBy(l=>l.CarroId);
                categoriaAtual = "Todos os carros";
            }
            else
            {
                // if(string.Equals("Esportivo", categoria, StringComparison.OrdinalIgnoreCase))
                // {
                //   carro =_carRentReposityory.Carros.
                //         Where(x => x.Categoria.Modelo.Equals("Esportivo"))
                //         .OrderBy(l=>l.StatusCarro);
                // }

                //if(string.Equals("Elegance", categoria, StringComparison.OrdinalIgnoreCase))
                // {
                //     carro = _carRentReposityory.Carros.
                //        Where(x => x.Categoria.Modelo.Equals("Elegance"))
                //        .OrderBy(l => l.StatusCarro);
                // }

                carros = _carRentReposityory.Carros
                     .Where(l => l.Categoria.Modelo.Equals(categoria))
                     .OrderBy(l => l.Marca);
                
                categoriaAtual = categoria;
            }

            var carroListViewModel = new CarroListViewModel
            {
                Carro = carros,
                CategoriaAtual=categoriaAtual,
            };



            return View(carroListViewModel);
        }

        public IActionResult Details(int carroId)
        {
            var carros = _carRentReposityory.Carros.FirstOrDefault(c => c.CarroId == carroId);
            return View(carros);
        }

        public ViewResult Search(string searchString)
        {
            IEnumerable<Carro> carros;
            string categoriaAtual = string.Empty;

            if(string.IsNullOrEmpty(searchString))
            {
                carros = _carRentReposityory.Carros.OrderBy(p => p.CarroId);
                categoriaAtual = "Todos os Carros";
            }
            else
            {
                carros = _carRentReposityory.Carros
                    .Where(p => p.Marca.ToLower().Contains(searchString.ToLower()));

                if (carros.Any())

                    categoriaAtual = "Carros";
                else
                    categoriaAtual = "Nenhum carro foi encontrado";
            }

            return View("~/Views/Carro/List.cshtml", new CarroListViewModel
            {
                Carro = carros,
                CategoriaAtual = categoriaAtual
            });

        }
    }
}

Controllers/ContatoController.cs
using Microsoft.AspNetCore.Mvc;

namespace CarRent.Controllers
{
    public class ContatoController : Controller
    {
        public IActionResult Index()
        {
            //Colocando autenticação nos contatos

            //if (User.Identity.IsAuthenticated)
            //{
            //    return View();

            //}
            //return RedirectToAction("Login", "Account");

            return View();
        }
    }
}

Views/Shared/_Carousel.cshtml
<div id="carouselRent" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="~/images/bmw-320i_formatada.jpg" class="d-block w-100" alt="" >
        </div>
        <div class="carousel-item">
            <img src="~/images/audio_formatado.jpg" class="d-block w-100" alt="" >
        </div>
        <div class="carousel-item">
            <img src="~/images/camaro_formatado.jpg" class="d-block w-100" alt="" >
        </div>
        <div class="carousel-item">
            <img src="~/images/fiat_formatado.jpg" class="d-block w-100" alt="" width= >
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselRent" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselRent" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

Views/Shared/_CarroResumo.cshtml
@model Carro
<div class="col-sm-4 col-md-4 col-lg-4">
    <p><img src="@Model.ImageCar" class="img-fluid" /></p>
    <h4>
    <a asp-controller="Carro" asp-action="Details" 
    asp-route-carroId="@Model.CarroId">@Model.Marca</a>
    </h4>
    <p>Cor : @Model.Cor</p>
    <p>Preço : @Model.Preco.ToString("c")</p>
    <p>Descrição : @Model.Descricao</p>
    <div>
        <p class="button">
            <a class="btn btn-primary" id="cartButton" asp-controller="CarrinhoCompra"
            asp-action="AdicionarItemNoCarrinhoCompra" asp-route-CarroId="@Model.CarroId">
             Incluir no Carrinho
            </a>
        </p>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CarRent</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CarRent.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/goldcar.jpg" width="100" height="100"/>
                    
                    </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            @await Component.InvokeAsync("CategoriaMenu")
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Carro" asp-action="List">Carros</a>
                           
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Contato" asp-action="Index">Contato</a>
                        </li>
                        <form class="navbar-form navbar-right" asp-controller="Carro" asp-action="Search" method="get">
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="Procurar produto" name="searchString" value="@ViewData["searchString"]">
                            </div>
                        </form>
                    </ul>
                    @await Component.InvokeAsync("CarrinhoCompraResumo")
                    @await Html.PartialAsync("_LoginPartial")
                    @if(User.IsInRole("Admin"))
                    {
                        <a class="nav-link text-light" asp-area="Admin" asp-controller="Admin" asp-action="Index">Admin</a>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CarRent - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>